### ISSUE TITLE
Feature request: Add option to stop propagation of dropdown close click

### ISSUE THREAD

**Issue by ssured** [cibernox/ember-basic-dropdown#172]
Thanks for the library, this is such a nice component to build smart apps, awesome!

Your code handles closing the dropdown when clicking outside the dropdown. In my usage scenario I have clickable routes behind the dropdown. Once you click next to the dropdown, the dropdown will close as expected, but also the click event on the row is triggered.

It would be really nice to be able to stop propagation of the click event outside the popup. Maybe we can reuse the `bubbles=false` which is possible on `link-to` and `action` elements?

**Comment by cibernox** [comment]
If I've understood the situation, you mean that you want to invalidate the click that closes the dropdown to also click on anything else.

I think that in your case you could get the behaviour you want by passing `overlay=true` to the dropdown content.

```hbs
    {{#basic-dropdown as |dd|}}
      {{#dd.trigger}}Click me!{{/dd.trigger}}
      {{#dd.content overlay=true}} {{!-- here! --}}
        content!
      {{/dd.content}}
    {{/basic-dropdown}}
```

This will render an invisible (unless you style it) overlay behind the dropdown. Since you are clicking in the transparent overlay, you won't be clicking on the thing behind it.

**Comment by ssured** [comment]
Awesome! That's what I was looking for. Thanks!

**Comment by ssured** [comment]
I was a little too enthousiastic. It seems the overlay does not capture the event which closes the dropdown. Where is this event handled?

**Comment by cibernox** [comment]
My bad, I forgot to metion that by default it is transparent to clicks because of this: https://github.com/cibernox/ember-basic-dropdown/blob/master/app/styles/ember-basic-dropdown.scss#L29

You can revert that CSS property and should work
