### ISSUE TITLE
Possible memory leak at 'triggerElement'

### ISSUE THREAD

**Issue by Haidy777** [cibernox/ember-basic-dropdown#180]
I've probably found a memory leak within your addon at the `triggerElement` property. It seems that it doesn't get cleared when the dropdown is destroyed. See https://github.com/emberjs/ember.js/issues/14626 for a full description and the results found by @robbiepitts [here](https://github.com/emberjs/ember.js/issues/14626#issuecomment-264174111)

(In our web-application we use `ember-power-select` 👍 )

**Comment by cibernox** [comment]
@Haidy777 I'm curious about how that can happen. The reference to the trigger element is stored in the component, so if the component is destroyed that reference should be garbage collected too.

**Comment by herom** [comment]
Is it possible that the added event handlers for `this.element` in the `ember-basic-dropdown/trigger` components `addMandatoryHandlers` method [see here](https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/trigger.js#L166) are never removed? This could lead to a memory leak like described, couldn't it?

**Comment by cibernox** [comment]
Events attached to a DOM element are cleaned if the element is destroyed. The kind of elements you have to be careful with are those attached outside the component, like events attached to the document or the window, but the component already cleans after itself: https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/trigger.js#L61-L65

There is another report of a memory leak, but I fail to see how that can happen since references are all internal to the component. What version of `ember-wormhole` do you have installed?

**Comment by Haidy777** [comment]
We are using `ember-wormhole 0.4.1`.
This should be the one which is shipped with `ember-basic-dropdown`.
Also we are using `renderInPlace = true` at all our dropdowns.

**Comment by cibernox** [comment]
I'll check if rendering in place makes any difference but if any id say that it would make leaking harder.

**Comment by Haidy777** [comment]
> if any id say that it would make leaking harder.

I would agree with that.
Maybe it is some weird combination with the `if`-helper and the dropdown which causes this.
