### ISSUE TITLE
Integration tests failing due to missing `service:-document`

### ISSUE THREAD

**Issue by anulman** [cibernox/ember-basic-dropdown#185]
I am currently unable to test a component's use of `{{ember-power-select}}` in an integration test, due to a missing injection related to `ember-basic-dropdown`'s use of `ember-wormhole`. Acceptance tests work fine.

For reference, I don't believe this deficiency is related directly to `ember-basic-dropdown` or its consumers, but folks may find this helpful when researching why their integration tests are failing.

To replicate:

- Create a custom component that implements an `ember-basic-dropdown`
- Render the custom component in an integration test
- Invoke the `clickTrigger` helper
- [your test should now be throwing]

The same symptoms have been observed in `ember-wormhole`; an issue is being tracked upstream at https://github.com/yapplabs/ember-wormhole/issues/77

h/t @chundabear, who first saw this and was instrumental in tracing the error :)

**Comment by cibernox** [comment]
Is this still a problem? I've been using this in glimmer2 and I didn't encounter this.

**Comment by anulman** [comment]
Not sure; will be in this project again this week and can verify in the test suite then.

Thanks @cibernox!

**Comment by simonihmig** [comment]
@cibernox See https://github.com/yapplabs/ember-wormhole/issues/77, it is related to Ember 2.6 and 2.7 only. But for those versions 0.5.1 fails for me, not just the tests, but also in the real app! Prevents me from upgrading my dependency in ember-bootstrap from 0.4.1. Same issue with other addons visible...

*Site note: I recall we once had a brief chat on Twitter about which Ember versions to test in ember-try, with you saying LTS (+ release, beta etc.) enough, while I am testing for all supported versions in ember-bootstrap (using the `versionCompatibily` feature of ember-try) because of the use of private APIs. While I was not using that many, ember-wormhole is! That way that error was detected actually...* 😉

**Comment by cibernox** [comment]
> Theory works.... in theory. - Anonymous
🤣

**Comment by anulman** [comment]
Manually registering `service:-document` as @gaurav0 described in https://github.com/yapplabs/ember-wormhole/issues/77#issuecomment-276827442 works for our suite 👍 

@cibernox would you be interested in a contrib that registers this for the consuming app if they're using Ember 2.6 / 2.7? Else others can stumble on this issue while Googling :)
