### ISSUE TITLE
Content width not matching trigger width

### ISSUE THREAD

**Issue by Ericky14** [cibernox/ember-basic-dropdown#208]
I am using ember-basic-dropdown(v0.19.4) from ember-power-select(1.0.3) which comes within ember-paper(v1.0.0-alpha.13) and is used from ember-paper-select.

The issue is that when an option that is below the first visible options is selected, the dropdown content width does not match the trigger width.

When the "reposition" function is called, the "calculatePosition" function variable seems to take on a function from paper-autocomplete-dropdown.js instead. I believe it was supposed to use one of the functions from utils/calculate-position, but that doesn't happen. I am not sure if this behavior is intended or if there is a problem. If it is an intentional behavior, then the problem is just to make if calculate the width correctly.

Example video of the issue: http://sendvid.com/sifwmukd

**Comment by cibernox** [comment]
I can't be totally sure, but I think that this is probably a bug in ember-paper, since it has its own repositioning logic: https://github.com/miguelcobain/ember-paper/blob/f07be761164cc97b55e2fa4ae45703e6619c9d4b/addon/components/paper-select-menu.js#L36-L168

Did you report that bug in ember-paper? I'd be glad to help there is needed.

**Comment by Ericky14** [comment]
I will report it there.

**Comment by cibernox** [comment]
I'm going to close and follow that issue
