### ISSUE TITLE
ember-concurrency version brakes my app

### ISSUE THREAD

**Issue by denzo** [cibernox/ember-basic-dropdown#220]
`ember-concurrency` version 7.11 is marked as "Latest release" which allows using tasks like this `this.myTask.perform();`.

`ember-basic-dropdown` uses version 7.19 which for some reason does not allow that functionality thus breaking my app.

**Comment by cibernox** [comment]
I think I have bad news for you then. That feature was removed from ember-concurrency because it had edge cases, and apparently bad ones, the ones you cannot sidestep, so it's not going to come back. https://github.com/machty/ember-concurrency/blob/master/CHANGELOG.md#0715

In the meanwhile ember-concurrency has continued to fix bugs, so I don't think there is much point in allowing a smaller version. You'll face this problem eventually (it had to do with tasks not being cleared when components were destroyed, leading to leaks and modifying destroyed components) and you'll have to refactor to `Ember.get`

**Comment by denzo** [comment]
Cool. Thanks for letting me know. I'll sort out my app.

**Comment by cibernox** [comment]
👍
