### ISSUE TITLE
Triggering the dropdown programmatically

### ISSUE THREAD

**Issue by Nikash** [cibernox/ember-basic-dropdown#330]
Is the only way to open the dropdown via javascript by triggering a native dom `mousedown` event? 

I've a use case when I want to open the dropdown when there is a different user interaction. I don't want to use the `ember-native-dom-helpers` since it's kind of meant for tests. Is there a more elegant solution than to trigger the native dom event manually similar to jQuery's `mousedown()`?

**Comment by cibernox** [comment]
I'm in the middle of a moving so I'll have 0 time until next week. Please ping me again if I haven't responded by next Wednesday.

**Comment by mhluska** [comment]
Did this get resolved? Im looking for a way to manually open the dropdown.

**Comment by cibernox** [comment]
There is two ways (two and a half). 

The "half" is that if you only want the dropdown to be open when first rendered, and nothing else, you can pass `initiallyOpen=true` to it. From than point on it behaves like if you opened yourself.

The first real way to open it at any moment is manually firing a `mousdown` event on the trigger, and it's the one I usually recommend because it's "safe".

The second and more powerful is to use the `registerAPI` (check http://ember-basic-dropdown.com/docs/api-reference) to grab a reference to the dropdown in your controller/component, and then you can just invoke anything.
P.e.

```hbs
{{#basic-dropdown registerAPI=(action (mut dropdown)) as |dd|}}...{{/basic-dropdown}}
```
```js
myHook() {
  this.get('dropdown').actions.open();
}
```

The reason why I don't usually recommend this one is because if you store a reference to the public API of the component in an object that never dies, like a controller or a service, and you forget to nullify that reference when you go to another route, you'll prevent the component from being garbage collected, so it's less "safe". If you store the reference in another component of you clear after yourself it's perfectly fine, it's just not safe by default.
