### ISSUE TITLE
clickWithinDropdownContent helper

### ISSUE THREAD

**Issue by caseywatts** [cibernox/ember-basic-dropdown#340]
In the app I'm working on, I often want to click a link inside a dropdown, and I want to narrow my `click` selector down to the dropdown content (which is wormhole'd away to another part of the DOM).

I currently do something like:
```
{{#basic-dropdown as |dd|}}
  {{#dd.trigger}}
    trigger
  {{/dd.trigger}}

  {{#dd.content}}
    <div data-test-target="drop-down-content">
      {{yield}}
    </div>
  {{/dd.content}}
{{/basic-dropdown}}
```

And in an acceptance test, this:
```
click('[data-test-target="drop-down-content"] a:contains(Create Plan')
```

I could imagine an alternative I'd prefer - a new helper sorta like `clickDropdown` that might function like I did above, but look something like this: 
```
clickWithinDropdownContent('a:contains(Create Plan)')
```

Thoughts? :)

**Comment by cibernox** [comment]
Well, you can also target `.ember-basic-dropdown-content .your-thing-inside` because dropdowns are mutually exclusive, so you know only one its opened at the same time. I don't think I want to expose any more helpers (and If I did, I wouldn't rely on jQuery, so your `:contains` pseudoselector shouldn't work).

At the end of the day I think that nested selector should be generally avoided and the best thing is to add the `data-test-` to the exact thing you want to click.

**Comment by cibernox** [comment]
I'm closing this as I think it's better to not add more test helpers as the same can be done just adding a class to the selector.
