### ISSUE TITLE
Failed to execute 'observe' on 'MutationObserver'

### ISSUE THREAD

**Issue by MB-web** [cibernox/ember-basic-dropdown#376]
When a dropdown is rendered through an ember island component (https://github.com/mitchlloyd/ember-islands), the dropdown will cause the error:
```
Failed to execute ‘observe’ on ‘MutationObserver’: parameter 1 is not of type ‘Node’.
  at i.startObservingDomMutations (vendor.js:29)
  at i.open (vendor.js:29)
  at invokeWithOnError (vendor.js:5)
  at s.flush (vendor.js:5)
  at l.flush (vendor.js:5)
  at p.end (vendor.js:5)
  at p.run (vendor.js:6)
  at u (vendor.js:11)
  at HTMLDocument.<anonymous> (vendor.js:32)
  at HTMLDocument.dispatch (vendor.js:4)
```
For some reason, this.dropdownElement seems not to be available in startObservingDomMutations().

If renderInPlace is set true, then the error does not happen.

Maybe someone had a similar issue?

**Comment by bendemboski** [comment]
I just saw this issue and tracked it down to `#ember-basic-dropdown-wormhole` not being present in the DOM. In my case it was because I was using it as a nested addon, and I wan't calling the [contentFor](https://github.com/cibernox/ember-basic-dropdown/blob/master/index.js#L25), like `ember-power-select` does [here](https://github.com/cibernox/ember-power-select/blob/master/index.js#L51).

**Comment by cibernox** [comment]
That makes sense and it's probably the cause, because using ember-islands the wormhole destination cannot be added automatically by the `contentFor` hook.

**Comment by nightire** [comment]
This issue happens in ember-twiddle as well, any ideas? (except `rendeInPlace=true`)

**Comment by ddoria921** [comment]
Curios as well how to fix this issue
