### ISSUE TITLE
[Feature request] Make it possible to control the state from outside the component

### ISSUE THREAD

**Issue by NindroidX** [cibernox/ember-basic-dropdown#410]
It would be awesome if this component also provided functionality to manage its state from the parent component (controlled component). With the current implementation it is not easy to close / open the dropdown based on the state in the parent component.

**Comment by cibernox** [comment]
That is already possible. If you check http://ember-basic-dropdown.com/docs/api-reference you'll see that there is a `registerAPI` action that receives the public API of the component on every state change (including on initial render).

If you store that object, you can use it as a remote controller to do pretty much anything you want with the component. 

Just take into account that if you store that object in an object that never gets destroyed (like a controller, a route or a service), you should delete that object when the dropdown itself is deleted, otherwise you would be preventing it to be garbage collected.

**Comment by NindroidX** [comment]
Ah, I see! Maybe this usage can be documented in a cookbook article or something?

However, I do think that a "real" controlled component (similar to how they work in React) would still be a good improvement though.

**Comment by cibernox** [comment]
Can I get an example of what a "real" controlled component looks like? You mean passing `this` to the outside so they can do anything they want with the component?

If that is the case, I am not doing it on purpose. The public API is an object with only the subject of functions I feel confortable sharing. I don't want to let people to access all the internals because otherwise I may break people's apps doing only internal refactors.

**Comment by NindroidX** [comment]
Ah sorry, I'm not sure what the correct naming is for what I mean. 

What I mean with "controlled" component is that the way it renders is based on the state of the parent component. In the case of this dropdown, it would be open/closed based on a boolean property in the parent and the only way it could change is by calling an action which is also passed in by the parent.

so in pseudo (don't mind the names):
```
{{#basic-dropdown isOpen=booleanValueInParent openHandler=(action "someActionWhichSetsTheBooleanToTrue") closeHandler=(action "someActionWhichSetsTheBooleanToFalse")}}
...
{{/dropdown}}
```
