### ISSUE TITLE
Erratic dropdown positioning

### ISSUE THREAD

**Issue by mariowilde** [cibernox/ember-basic-dropdown#527]
Hello,

we are currently using ember-power-select-typeahead@0.8.0 together with ember-basic-dropdown@2.0.13 and observe the following bug:
The vertical position of one of our power-select-typeahead dropdowns seems to update erratically, when the power-select input is changed.
The dropdown is configured to open upwards, but sometimes there is a significant gap between the lower edge of the dropdown and the upper edge of the trigger (as shown in the appended sketch). At other times the dropdown is positioned to low such that it's upper edge is positioned at the upper edge of the trigger. The problem occurs most often when only a single element has been found.

![Zeichnung](https://user-images.githubusercontent.com/9639432/72596083-924a7c80-390b-11ea-8c27-0954b2da139a.png)

The bug seems to have been introduced in version 2.0.12 by pull request #521.
Reverting  the changes made to addon/components/basic-dropdown-content.js fixes the issue.

**Comment by cibernox** [comment]
Interesting, I didn't expect that to have backwards-incomptable consequence. Is there any chance you can spawn a simple repo where it can be reproduced?

**Comment by mariowilde** [comment]
Here you go. mariowilde/ember-basic-dropdown-527-reproduction

**Comment by seanCodes** [comment]
I’ve also run into this issue. Glad to see it wasn’t just me! 😅

I did some investigating and it looks like the MutationObserver logic in `ember-basic-dropdown` isn’t triggering a reposition when list items are added/removed. This strategy works just fine when the dropdown is positioned below, since height changes don’t affect its position, but when rendering above, the dropdown needs to be repositioned any time the contents of the dropdown changes. The regression seems to have been introduced with cibernox/ember-basic-dropdown#517/cibernox/ember-basic-dropdown#518.

It seems like there are a few possible solutions:

1. Update [`BasicDropdownContent#setupMutationObserver`](https://github.com/cibernox/ember-basic-dropdown/blob/v2.0.13/addon/components/basic-dropdown-content.js#L187) to take above/below positioning into account when determining whether a mutation should cause a reposition. The method would have to be made aware of its current vertical positioning and the  mutations that would trigger repositions would need to be determined.
2. Revert the above changes that caused the regression and reposition on every add/remove mutation. Require users to take advantage of `@shouldReposition` if they want to ignore certain mutations.
3. Explicitly call the `BasicDropdownContent#runloopAwareReposition` action after a search occurs. This might be a good workaround but it wouldn’t address the root cause in `ember-basic-dropdown`.
4. Modify the `calculateWormholedPosition` logic to position the dropdown relative to the `bottom` of the dropdown-anchor when rendering above, rather than using `top`. This would be a much simpler CSS-only solution and wouldn’t require any changes to the current MutationObserver logic. 

   The only downside to this approach would be that, while the dropdown is open, adding content below the trigger (and effectively changing the dropdown-anchor’s height) would mess up the dropdown’s position. (Technically this issue already exists, but in reverse: adding content above the trigger will mess up the dropdown’s position. However dynamically adding content above existing content is probably much less common than adding it below, e.g. infinite scroll.)

@cibernox any preference on which approach to take? I have a working version of the 4th option but not sure if the tradeoff mentioned would be a dealbreaker. Either way I have some time and could submit a PR with a fix.

**Comment by ShepherdHawkeye** [comment]
Just to comment on the impact of this bug. I got here because we noticed this behavior in Ember Power Select. You can even see it in the [documentation](https://ember-power-select.com/docs/the-search).

Scroll down so that the list renders above the trigger and then type into the search box. The list will get shorter without repositioning. This creates the gap that the OP reported.

[The docs](https://2-x.ember-power-select.com/docs/the-search) for version 2.x don't have this issue.

**Comment by mariowilde** [comment]
@cibernox I opened pr #596 to fix this issue. Please take a look.

**Comment by cibernox** [comment]
Thanks for the fix. Today I focused of getting CI fixed and migrating to github actions (finally!) so I have more confidence merging PRs.

I'll review this over the weekend, or at least I'll try.

**Comment by mariowilde** [comment]
Please don't forget this MR. :pleading_face:
