### ISSUE TITLE
Glimmer error when ember-basic-dropdown 2.0.15 and ember-power-select 4.0.0 are installed together

### ISSUE THREAD

**Issue by Jakeii** [cibernox/ember-basic-dropdown#551]
When these 2 plugins are installed at the same time I got this error
```
Uncaught (in promise) Error: Could not find module `ember-compatibility-helpers` imported from `@glimmer/component/index`
```

Version 2.x of ember-basic-dropdown  and 4.x of ember-power select was installed by default, was solved when I updated ember-basic-dropdown to 3.x

**Comment by kevinansfield** [comment]
I ran into this same issue when upgrading `ember-power-select`. For me bumping `ember-power-datepicker` which has a dependency on `ember-basic-dropdown` resolved things.

Wish there was a better error message/easier way to debug the root cause, took quite a while to narrow it down! 🤞 adding some of the above keywords will help anyone else who hits this find it when Googling
