### ISSUE TITLE
Deprecation: glimmer.private-in-element

### ISSUE THREAD

**Issue by fran-worley** [cibernox/ember-basic-dropdown#570]
When running Ember v3.20.3 and EBD v3.0.7 we're getting the following deprecation error:

DEPRECATION: The use of the private `{{-in-element}}` is deprecated, please refactor to the public `{{in-element}}`. ('ember-basic-dropdown/templates/components/basic-dropdown-content.hbs' @ L1:C0)  [deprecation id: glimmer.private-in-element]

**Comment by cibernox** [comment]
Ok, this is a tricky one. We're using `ember-maybe-in-element` and `ember-in-element-polyfill`. For some reason I haven't quite understood yet, since both addons do their magic using an AST transform, seems that the order in which they run is either the reverse of what we want OR they run in the right order but for some reason the second AST transform can't see the changes made but the first one.

If I fix this the addon would require Ember 3.20 or greater. 

I think we will have to live with the deprecation for a bit longer while I get someone from the ember team to explain exactly what is going on and how to fix it (I suspect it's a bug in how ember-cli runs AST transforms)

**Comment by raido** [comment]
I guess work done over here - https://github.com/DockYard/ember-maybe-in-element - will eventually resolve this here as well?

**Comment by cibernox** [comment]
Yup, I should have some time today to update this. I might have to drop 3.12, but since 3.20 is an LTS that's probably fine, I would still be supporting the last two LTS

**Comment by cibernox** [comment]
@fran-worley @raido 3.0.8 should fix that deprecation 🎉
