### ISSUE TITLE
Types need to be published

### ISSUE THREAD

**Issue by tansongyang** [cibernox/ember-basic-dropdown#660]
We're using Ember with TypeScript. Got latest this morning (v4.0.5) and we can't compile because TS can't find the types for `ember-get-config`. Looking in my `node_modules`, I can confirm that the `types` directory is missing.

I believe the fix involves adding `"types": "./path/to/index.d.ts"` in the `package.json`, though there may be more steps.

![image](https://user-images.githubusercontent.com/9488719/160145430-528fb858-85ca-40ae-87ca-4fca722c5313.png)

**Comment by bertdeblock** [comment]
I'd rather see `ember-get-config` removed again. v1 and v2 were made in an attempt to make the addon compatible with Embroider, but at the moment, it isn't. The reason why people think it's compatible with Embroider is because Embroider ships with [a compat adapter for `ember-get-config`](https://github.com/embroider-build/embroider/blob/main/packages/compat/src/compat-adapters/ember-get-config.ts).
[Disabling the compat adapter](https://github.com/mansona/ember-get-config/pull/43) shows that the addon is not yet compatible on its own.
Also, the config object returned isn't an actual reference to the app's config.
Resolving the config via the owner (like it was before) is still the best and safest way to get the app's actual config object and doesn't require an additional dependency.
