### ISSUE TITLE
v7.0.0 is not published to NPM

### ISSUE THREAD

**Issue by jelhan** [cibernox/ember-basic-dropdown#698]
v7.0.0 has a changelog entry and a git tag. But it seems to be not published to NPM. Seems as if something went wrong when releasing it. Please have a look.

**Comment by cibernox** [comment]
yes, I am aware. It's because typescript would not build on 7.0.0 because of some weird type mismatch in types with ember-resolver that I wasn't able to solve. I need to take another look but it's quite weird because it doesn't seem to be coming from the addon's code.

**Comment by mkszepp** [comment]
maybe it is caused with my changes? https://github.com/cibernox/ember-basic-dropdown/commit/aa93fe11c4c835346f505c25c784ca022b50e460#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL89-L106

**Comment by cibernox** [comment]
Not by those changes at least. You can reproduce the problem running `ember ts:precompile`. There is one legitimate typescript problem in the codebase that was easy to fix but then the rest of the type problems come from dependencies having mismatched types. Which is weird because I though that starting with Ember 4.8 typescript support didn't require to use `@types/*` packages.

**Comment by mkszepp** [comment]
@cibernox Fix for `ember ts:precompile` commitet

**Comment by cibernox** [comment]
@mkszepp and 7.0 has been published!! Now I should go and update ember-power-select too to use this new version.

**Comment by mkszepp** [comment]
@cibernox awesome thanks!

Note: i think you have forget to run `ember ts:clean` after run `ember ts:precompile` locally (because there were commitet some files, which here not necessray (https://github.com/cibernox/ember-basic-dropdown/commit/98b22507fb1cf18abd02d9b1d39270f129353651#diff-4e0d6fc9929661dc1090ddff7cd9bae6650bd0e1cd089988d70f87548ae65a68)

**Comment by cibernox** [comment]
I don't remember those files being generated before. I'll update the publish script
