### ISSUE TITLE
Unexpected identifier 'willDestroy' after the 'override'

### ISSUE THREAD

**Issue by pzubar** [cibernox/ember-basic-dropdown#703]
Hello! After bumping the `ember-power-select` to the latest version, it seems like the `ember-basic-dropdown` started to fail in the runtime. I suspect `override` is the issue here and should not be a part of a js code. However, unfortunately, I have no idea how to fix the issue and will be grateful for the help.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/36226946/235932946-fd9e19f9-def3-4d1c-aa1b-a051483150dd.png">

```
"ember-power-select": "^7.0.0",
"ember-source": "~3.28.11"
```

**Comment by Gorzas** [comment]
After a day investigating, I think the issue is related with some mess on Ember versions. You may be loading Ember v3 and v4 at the same time. Maybe the source code is using an updated Ember version but you could have some dependencies attached to an older Ember version.

What I did to fix the issue:
- clean node_modules and lock files
- install dependencies (in my case, using yarn workspaces)
- updated the versions of `ember-source` to at least `4.0.0`

I hope this could work for you, @pzubar 

[This issue](https://github.com/embroider-build/embroider/issues/1378) send me in the right track, in case you need more context about the issue.

**Comment by gorner** [comment]
@Gorzas OP said they are still on Ember 3.28, I am still on Ember 3.28 as well (still working on upgrading to Octane, and no dependency on ember-source 4+ anywhere in my package-lock) and am getting the same result. 

e-basic-dropdown v7 [claims](https://github.com/cibernox/ember-basic-dropdown/blob/master/CHANGELOG.md#700) to remain compatible with Ember 3.28. It would be reasonable if the maintainer wants to make future versions of this addon Ember 4+ only (especially now that there's an Ember 5) but it's a breaking change not indicated in the changelog.

**Comment by Gorzas** [comment]
@gorner Sorry, in my case I had references to different Ember versions in my yarn.lock file and I only required the two first steps to fix it. I think my previous comment isn't a good explanation, we had the issue when we were in the middle of an Ember upgrade, that's why I wrote the last point. Sorry for the confusion.

**Comment by gorner** [comment]
@Gorzas No worries, thanks for clarifying.

**Comment by ArnaudWeyts** [comment]
I was having a similar issue, but on build time. What fixed it for me was running `yarn dedupe @babel/parser` to make sure there's only one version being used

**Comment by gorner** [comment]
Tried again with EBD v7.2.2 and everything is now working fine. We are still on Ember 3.28 but it's possible that other changes to our build tree in the meantime (such as removing/updating the last dependencies that used ember-cli-babel v6) resulted in it working this time.

**Comment by mkszepp** [comment]
Let me know if this issue occures also on v8 of ebp with eps
