### ISSUE TITLE
convert to v2?

### ISSUE THREAD

**Issue by betocantu93** [cibernox/ember-basic-dropdown#719]
Hello !! I'm wrapping ember-power-select, thus wrapper ember-basic-dropdown for ember-eui https://github.com/prysmex/ember-eui/tree/master/packages/core/addon/components/eui-combo-box

I'm working in migrating embr-eui to v2, which removes the ember-cli classic build pipeline, so no more `contentFor` etc

Most of these apis can be replaced by new paradigms.

On my v2 addon, as far as I know since I don't have contentFor anymore, https://github.com/prysmex/ember-eui/blob/3f2111a93c8afa11a1fad3623e33acefdcad68a5/packages/core/index.js#L55, 

I need to add instructions like: 

Please add in your index.html

`<div id="ember-basic-dropdown-wormhole"></div>`;

Which makes me want to migrate both ember-basic-dropdown and ember-power-select to new v2 SPEC and provide clear instructions on each package to how to do the stuff that the `included` and `contentFor` from both packages did in classic addons

**Comment by mkszepp** [comment]
Hi @betocantu93,

atm, this addon (and also other ember-power addon's) are atm not ready for v2.

The migration to v2 brings for this addon and also other a lot of braking changes.
I have already analysed a little bit the migration for this addon and also other ember-power addons, but since now i havn't started the migration.

I'm sure, that there is time to migrated this and also other ember-power addons to v2.

My plan was, to make a release in the next days for ember-basic-dropdown & ember-power-select and than i think we can start to migrate to a v2 addon.

**Comment by betocantu93** [comment]
Aight! Let me know if you need help. Thanks

**Comment by mkszepp** [comment]
@betocantu93 i think, i have now completely converted to v2 addon see PR (https://github.com/cibernox/ember-basic-dropdown/pull/728).

Also docs were updated for this changes...

In the next days i will prepare a beta release and than we need to do the same for `ember-power-select` and making tests with basic dropdown as v2 addon

**Comment by betocantu93** [comment]
Wow! Nice, will have a look at it.  Great job and thanks for working on this.

**Comment by mkszepp** [comment]
@betocantu93 sry for my delay... there is now released the addon as v2 addon (tag `8.0.0-beta.0`)
Also `ember-power-select` was migrated to a v2 addon and released as with tag `8.0.0-beta.0`

**Comment by NullVoxPopuli** [comment]
been testing the the beta.3/beta.2 of power-select/basic-dropdown, in an app with > 13k tests, and things are going smoothly.

**Comment by mkszepp** [comment]
@NullVoxPopuli thank you for feedback! The plan is to hold beta for next days. Maybe we get some additional feedbacks & hofully no bug reports 😅.
