### ISSUE TITLE
Touch Device "tapping" to close the dropdown doesn't work

### ISSUE THREAD

**Issue by Haidy777** [cibernox/ember-basic-dropdown#80]
If a dropdown is open, and you tab on any other element, the dropdown won't close as it does on a `click` based event.

This seems to happen because there is no global listener for `touchstart` as there is for `mousedown`.
See [addon/components/basic-dropdown/content.js](https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/content.js#L35).

Simply adding `this.get('appRoot').addEventListener('touchstart', this.handleRootMouseDown, true);` seems to fix it. If you want I can provide a PR.

**Comment by cibernox** [comment]
@Haidy777 I think the fix is a bit more involved, because I'd like to allow people to scroll with the dropdown open, so instead we should detect "taps". Detecting taps is a bit more involved since it requires a `touchstart` followed by a `touchend` and check that no `touchmove` is fired between both.

But yes, this is a bug.

**Comment by Haidy777** [comment]
So something like (this)[https://github.com/cibernox/ember-power-select/blob/a6c2a89588fbb35eefb236a6ad597aac71974768/addon/components/power-select/options.js#L28] solution?

**Comment by cibernox** [comment]
@Haidy777 exactly like that (which maybe should be extracted to some helper)
